# Copyright (c) 2010-2021, Lawrence Livermore National Security, LLC. Produced
# at the Lawrence Livermore National Laboratory. All Rights reserved. See files
# LICENSE and NOTICE for details. LLNL-CODE-806117.
#
# This file is part of the MFEM library. For more information and source code
# availability visit https://mfem.org.
#
# MFEM is free software; you can redistribute it and/or modify it under the
# terms of the BSD-3 license. We welcome feedback and contributions, see file
# CONTRIBUTING.md for details.

name: repo-check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  copyright-check:
    runs-on: ubuntu-latest

    steps:
    - name: checkout mfem
      uses: actions/checkout@v2
      with:
        path: mfem

    - name: copyright check
      run: |
        cd mfem
        if git grep -l "^#.*\-2020" > matches.txt
        then
          echo "Please update the following files to Copyright (c) 2010-2021:"
          cat matches.txt
          exit 1
        else
          echo "No outdated copyright found."
        fi
